// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security_service.proto

package ds.SecurityService;

public interface AccessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool has_access = 1;</code>
   */
  boolean getHasAccess();
}
