// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security_service.proto

package ds.SecurityService;

public interface AccessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string room_id = 2;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string room_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();
}
