// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security_service.proto

package ds.SecurityService;

public interface ActivityEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActivityEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_type = 1;</code>
   */
  java.lang.String getEventType();
  /**
   * <code>string event_type = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
