// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security_service.proto

package ds.SecurityService;

public final class SecurityServiceImpl {
  private SecurityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccessResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivityEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivityEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026security_service.proto\"1\n\rAccessReques" +
      "t\022\017\n\007user_id\030\001 \001(\t\022\017\n\007room_id\030\002 \001(\t\"$\n\016A" +
      "ccessResponse\022\022\n\nhas_access\030\001 \001(\010\"8\n\rAct" +
      "ivityEvent\022\022\n\nevent_type\030\001 \001(\t\022\023\n\013descri" +
      "ption\030\002 \001(\t2\272\001\n\017SecurityService\0220\n\013Check" +
      "Access\022\016.AccessRequest\032\017.AccessResponse\"" +
      "\000\0229\n\023MonitorRoomActivity\022\016.AccessRequest" +
      "\032\016.ActivityEvent\"\0000\001\022:\n\023CheckMultipleAcc" +
      "ess\022\016.AccessRequest\032\017.AccessResponse\"\000(\001" +
      "B+\n\022ds.SecurityServiceB\023SecurityServiceI" +
      "mplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AccessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AccessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccessRequest_descriptor,
        new java.lang.String[] { "UserId", "RoomId", });
    internal_static_AccessResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AccessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccessResponse_descriptor,
        new java.lang.String[] { "HasAccess", });
    internal_static_ActivityEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ActivityEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivityEvent_descriptor,
        new java.lang.String[] { "EventType", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
