// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingService.proto

package ds.LightService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
