// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingService.proto

package ds.LightService;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 brightness = 1;</code>
   */
  int getBrightness();
}
