// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingService.proto

package ds.LightService;

public final class LightServiceImpl {
  public LightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025lightingService.proto\"0\n\014LightRequest\022" +
      "\014\n\004isOn\030\001 \001(\010\022\022\n\nbrightness\030\002 \001(\005\"#\n\rLig" +
      "htResponse\022\022\n\nbrightness\030\001 \001(\005\"\007\n\005Empty2" +
      "\245\001\n\014LightService\022$\n\tturnOnOff\022\r.LightReq" +
      "uest\032\006.Empty\"\000\0229\n\024getCurrentBrightness\022\r" +
      ".LightRequest\032\016.LightResponse\"\0000\001\0224\n\rset" +
      "Brightness\022\r.LightRequest\032\016.LightRespons" +
      "e\"\000(\0010\001B%\n\017ds.LightServiceB\020LightService" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightRequest_descriptor,
        new java.lang.String[] { "IsOn", "Brightness", });
    internal_static_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightResponse_descriptor,
        new java.lang.String[] { "Brightness", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
