// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingService.proto

package ds.LightService;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isOn = 1;</code>
   */
  boolean getIsOn();

  /**
   * <code>int32 brightness = 2;</code>
   */
  int getBrightness();
}
