// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HAVC_service.proto

package ds.HavcService;

public interface ConfirmationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConfirmationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
