// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HAVC_service.proto

package ds.HavcService;

public final class HavcServiceImpl {
  private HavcServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfirmationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfirmationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemperatureValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemperatureValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HAVC_service.proto\")\n\022TemperatureReque" +
      "st\022\023\n\013temperature\030\001 \001(\005\"&\n\023ConfirmationM" +
      "essage\022\017\n\007message\030\001 \001(\t\"\'\n\020TemperatureVa" +
      "lue\022\023\n\013temperature\030\001 \001(\0052\322\001\n\013HvacService" +
      "\022=\n\016setTemperature\022\023.TemperatureRequest\032" +
      "\024.ConfirmationMessage\"\000\022B\n\024getTemperatur" +
      "eStream\022\023.TemperatureRequest\032\021.Temperatu" +
      "reValue\"\0000\001\022@\n\022controlTemperature\022\021.Temp" +
      "eratureValue\032\021.TemperatureValue\"\000(\0010\001B#\n" +
      "\016ds.HavcServiceB\017HavcServiceImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemperatureRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_ConfirmationMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfirmationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfirmationMessage_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_TemperatureValue_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TemperatureValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemperatureValue_descriptor,
        new java.lang.String[] { "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
