// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HAVC_service.proto

package ds.HavcService;

public interface TemperatureValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TemperatureValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
